// unité pour définir un tableau d'arbres binaires
// arbres binaires générés aléatoirement
// unité automatiquement générée par programme le 19-11-08
unit U_Exemples_Arbres ;
interface
uses U_Arbre ;
const N = 50;
var exemple : array[0..N-1] of ARBRE ;

implementation

initialization
  exemple[0] := creerArbre(16,creerArbre(178,creerArbre(147,creerArbre(30,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(61,ARBREVIDE,creerArbre(144,ARBREVIDE,ARBREVIDE))),creerArbre(139,creerArbre(123,creerArbre(188,ARBREVIDE,creerArbre(147,creerArbre(179,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(38,ARBREVIDE,creerArbre(167,ARBREVIDE,ARBREVIDE))),creerArbre(179,creerArbre(140,ARBREVIDE,ARBREVIDE),creerArbre(6,ARBREVIDE,ARBREVIDE)))) ;
  exemple[1] := creerArbre(61,creerArbre(65,creerArbre(12,ARBREVIDE,ARBREVIDE),creerArbre(45,creerArbre(93,ARBREVIDE,ARBREVIDE),creerArbre(1,ARBREVIDE,creerArbre(121,ARBREVIDE,creerArbre(128,ARBREVIDE,ARBREVIDE))))),creerArbre(94,creerArbre(80,creerArbre(122,ARBREVIDE,creerArbre(114,ARBREVIDE,ARBREVIDE)),ARBREVIDE),creerArbre(76,creerArbre(165,ARBREVIDE,ARBREVIDE),ARBREVIDE))) ;
  exemple[2] := creerArbre(67,creerArbre(47,creerArbre(72,creerArbre(3,creerArbre(86,ARBREVIDE,ARBREVIDE),creerArbre(28,creerArbre(120,ARBREVIDE,ARBREVIDE),creerArbre(37,creerArbre(169,ARBREVIDE,ARBREVIDE),ARBREVIDE))),creerArbre(104,creerArbre(107,ARBREVIDE,ARBREVIDE),creerArbre(30,ARBREVIDE,ARBREVIDE))),ARBREVIDE),creerArbre(56,creerArbre(94,ARBREVIDE,creerArbre(174,creerArbre(36,ARBREVIDE,ARBREVIDE),ARBREVIDE)),ARBREVIDE)) ;
  exemple[3] := creerArbre(145,creerArbre(133,creerArbre(172,ARBREVIDE,ARBREVIDE),creerArbre(82,ARBREVIDE,creerArbre(0,ARBREVIDE,ARBREVIDE))),creerArbre(36,creerArbre(60,ARBREVIDE,ARBREVIDE),creerArbre(186,creerArbre(173,ARBREVIDE,ARBREVIDE),creerArbre(152,ARBREVIDE,ARBREVIDE)))) ;
  exemple[4] := creerArbre(98,creerArbre(116,creerArbre(180,creerArbre(152,ARBREVIDE,creerArbre(174,ARBREVIDE,ARBREVIDE)),creerArbre(182,ARBREVIDE,ARBREVIDE)),creerArbre(95,creerArbre(24,ARBREVIDE,creerArbre(96,ARBREVIDE,ARBREVIDE)),creerArbre(3,ARBREVIDE,ARBREVIDE))),creerArbre(177,creerArbre(172,ARBREVIDE,creerArbre(82,ARBREVIDE,ARBREVIDE)),creerArbre(103,creerArbre(8,ARBREVIDE,ARBREVIDE),creerArbre(40,ARBREVIDE,ARBREVIDE)))) ;
  exemple[5] := creerArbre(170,creerArbre(102,creerArbre(156,creerArbre(192,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(23,creerArbre(32,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(102,creerArbre(169,ARBREVIDE,ARBREVIDE),creerArbre(11,ARBREVIDE,creerArbre(49,creerArbre(81,ARBREVIDE,ARBREVIDE),ARBREVIDE)))) ;
  exemple[6] := creerArbre(196,creerArbre(104,creerArbre(154,ARBREVIDE,ARBREVIDE),creerArbre(180,ARBREVIDE,ARBREVIDE)),creerArbre(104,creerArbre(141,ARBREVIDE,creerArbre(147,ARBREVIDE,creerArbre(154,ARBREVIDE,ARBREVIDE))),creerArbre(62,creerArbre(20,ARBREVIDE,ARBREVIDE),ARBREVIDE))) ;
  exemple[7] := creerArbre(62,creerArbre(83,creerArbre(116,ARBREVIDE,creerArbre(114,ARBREVIDE,creerArbre(91,ARBREVIDE,ARBREVIDE))),creerArbre(176,creerArbre(64,ARBREVIDE,ARBREVIDE),creerArbre(53,ARBREVIDE,ARBREVIDE))),creerArbre(109,ARBREVIDE,creerArbre(142,creerArbre(182,creerArbre(96,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(168,creerArbre(15,ARBREVIDE,ARBREVIDE),ARBREVIDE)))) ;
  exemple[8] := creerArbre(149,creerArbre(82,creerArbre(21,creerArbre(21,ARBREVIDE,ARBREVIDE),creerArbre(0,ARBREVIDE,ARBREVIDE)),ARBREVIDE),creerArbre(131,creerArbre(9,ARBREVIDE,creerArbre(113,creerArbre(135,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(120,ARBREVIDE,creerArbre(81,ARBREVIDE,ARBREVIDE)))) ;
  exemple[9] := creerArbre(63,creerArbre(77,creerArbre(176,creerArbre(22,ARBREVIDE,creerArbre(183,ARBREVIDE,ARBREVIDE)),creerArbre(31,ARBREVIDE,creerArbre(103,ARBREVIDE,ARBREVIDE))),creerArbre(188,ARBREVIDE,creerArbre(163,creerArbre(100,ARBREVIDE,ARBREVIDE),ARBREVIDE))),creerArbre(23,creerArbre(3,ARBREVIDE,ARBREVIDE),ARBREVIDE)) ;
  exemple[10] := creerArbre(102,creerArbre(6,creerArbre(105,creerArbre(158,creerArbre(0,ARBREVIDE,ARBREVIDE),creerArbre(20,ARBREVIDE,ARBREVIDE)),creerArbre(76,creerArbre(137,ARBREVIDE,ARBREVIDE),creerArbre(174,ARBREVIDE,creerArbre(72,ARBREVIDE,ARBREVIDE)))),creerArbre(70,creerArbre(167,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(84,creerArbre(115,ARBREVIDE,ARBREVIDE),creerArbre(149,ARBREVIDE,creerArbre(80,creerArbre(181,ARBREVIDE,ARBREVIDE),creerArbre(127,ARBREVIDE,ARBREVIDE))))) ;
  exemple[11] := creerArbre(74,creerArbre(87,creerArbre(118,creerArbre(110,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(48,creerArbre(8,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(85,ARBREVIDE,creerArbre(106,creerArbre(99,creerArbre(148,creerArbre(154,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(42,ARBREVIDE,ARBREVIDE)),ARBREVIDE))) ;
  exemple[12] := creerArbre(59,ARBREVIDE,creerArbre(167,creerArbre(69,ARBREVIDE,ARBREVIDE),creerArbre(16,ARBREVIDE,creerArbre(51,creerArbre(8,creerArbre(28,ARBREVIDE,creerArbre(48,ARBREVIDE,ARBREVIDE)),ARBREVIDE),creerArbre(122,creerArbre(107,ARBREVIDE,ARBREVIDE),ARBREVIDE))))) ;
  exemple[13] := creerArbre(162,creerArbre(82,creerArbre(96,creerArbre(81,ARBREVIDE,ARBREVIDE),ARBREVIDE),ARBREVIDE),creerArbre(130,creerArbre(126,creerArbre(51,creerArbre(11,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(195,ARBREVIDE,ARBREVIDE)),creerArbre(4,ARBREVIDE,ARBREVIDE))) ;
  exemple[14] := creerArbre(88,creerArbre(190,creerArbre(175,ARBREVIDE,creerArbre(107,ARBREVIDE,ARBREVIDE)),creerArbre(56,creerArbre(162,creerArbre(55,creerArbre(1,ARBREVIDE,ARBREVIDE),creerArbre(2,creerArbre(99,ARBREVIDE,ARBREVIDE),creerArbre(40,ARBREVIDE,ARBREVIDE))),creerArbre(163,ARBREVIDE,ARBREVIDE)),creerArbre(152,ARBREVIDE,creerArbre(152,ARBREVIDE,creerArbre(152,ARBREVIDE,creerArbre(31,ARBREVIDE,ARBREVIDE)))))),creerArbre(159,ARBREVIDE,creerArbre(195,ARBREVIDE,ARBREVIDE))) ;
  exemple[15] := creerArbre(198,creerArbre(129,ARBREVIDE,creerArbre(18,creerArbre(162,ARBREVIDE,ARBREVIDE),creerArbre(156,ARBREVIDE,creerArbre(52,creerArbre(181,ARBREVIDE,ARBREVIDE),ARBREVIDE)))),creerArbre(162,creerArbre(64,creerArbre(80,ARBREVIDE,ARBREVIDE),creerArbre(125,ARBREVIDE,creerArbre(0,ARBREVIDE,ARBREVIDE))),ARBREVIDE)) ;
  exemple[16] := creerArbre(45,creerArbre(67,creerArbre(32,creerArbre(98,ARBREVIDE,ARBREVIDE),ARBREVIDE),ARBREVIDE),creerArbre(190,creerArbre(93,creerArbre(164,ARBREVIDE,creerArbre(29,ARBREVIDE,ARBREVIDE)),creerArbre(149,ARBREVIDE,ARBREVIDE)),creerArbre(186,creerArbre(149,ARBREVIDE,ARBREVIDE),creerArbre(63,creerArbre(162,ARBREVIDE,ARBREVIDE),ARBREVIDE)))) ;
  exemple[17] := creerArbre(130,creerArbre(190,creerArbre(83,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(139,creerArbre(190,creerArbre(4,creerArbre(123,creerArbre(170,ARBREVIDE,ARBREVIDE),creerArbre(120,ARBREVIDE,ARBREVIDE)),ARBREVIDE),creerArbre(185,ARBREVIDE,ARBREVIDE)),creerArbre(36,creerArbre(195,ARBREVIDE,ARBREVIDE),ARBREVIDE))) ;
  exemple[18] := creerArbre(14,ARBREVIDE,creerArbre(100,creerArbre(176,creerArbre(192,creerArbre(55,ARBREVIDE,creerArbre(191,ARBREVIDE,ARBREVIDE)),creerArbre(38,creerArbre(16,creerArbre(185,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(42,ARBREVIDE,ARBREVIDE))),creerArbre(18,creerArbre(99,ARBREVIDE,creerArbre(39,ARBREVIDE,ARBREVIDE)),ARBREVIDE)),ARBREVIDE)) ;
  exemple[19] := creerArbre(76,creerArbre(53,creerArbre(194,creerArbre(107,creerArbre(15,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(83,ARBREVIDE,creerArbre(114,ARBREVIDE,ARBREVIDE))),creerArbre(170,creerArbre(47,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(124,creerArbre(94,creerArbre(140,creerArbre(193,ARBREVIDE,ARBREVIDE),creerArbre(52,ARBREVIDE,ARBREVIDE)),creerArbre(84,creerArbre(115,creerArbre(183,creerArbre(25,ARBREVIDE,ARBREVIDE),ARBREVIDE),ARBREVIDE),ARBREVIDE)),creerArbre(40,ARBREVIDE,ARBREVIDE))) ;
  exemple[20] := creerArbre(118,creerArbre(64,creerArbre(59,creerArbre(22,ARBREVIDE,creerArbre(83,ARBREVIDE,creerArbre(38,ARBREVIDE,ARBREVIDE))),ARBREVIDE),creerArbre(32,ARBREVIDE,creerArbre(40,creerArbre(183,ARBREVIDE,creerArbre(140,ARBREVIDE,ARBREVIDE)),creerArbre(67,ARBREVIDE,creerArbre(183,ARBREVIDE,ARBREVIDE))))),creerArbre(174,ARBREVIDE,creerArbre(105,ARBREVIDE,creerArbre(160,ARBREVIDE,ARBREVIDE)))) ;
  exemple[21] := creerArbre(11,creerArbre(180,creerArbre(186,creerArbre(60,creerArbre(138,ARBREVIDE,ARBREVIDE),ARBREVIDE),ARBREVIDE),creerArbre(195,ARBREVIDE,creerArbre(91,ARBREVIDE,ARBREVIDE))),creerArbre(75,ARBREVIDE,creerArbre(106,creerArbre(97,creerArbre(182,creerArbre(5,ARBREVIDE,ARBREVIDE),creerArbre(58,creerArbre(160,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(79,creerArbre(184,ARBREVIDE,ARBREVIDE),creerArbre(37,ARBREVIDE,creerArbre(58,ARBREVIDE,creerArbre(55,ARBREVIDE,ARBREVIDE))))),ARBREVIDE))) ;
  exemple[22] := creerArbre(40,creerArbre(61,creerArbre(52,ARBREVIDE,creerArbre(32,creerArbre(33,ARBREVIDE,ARBREVIDE),creerArbre(132,ARBREVIDE,ARBREVIDE))),creerArbre(164,creerArbre(82,creerArbre(117,creerArbre(74,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(199,ARBREVIDE,ARBREVIDE)),ARBREVIDE)),creerArbre(140,creerArbre(44,ARBREVIDE,creerArbre(161,ARBREVIDE,ARBREVIDE)),creerArbre(13,creerArbre(28,ARBREVIDE,ARBREVIDE),creerArbre(152,ARBREVIDE,ARBREVIDE)))) ;
  exemple[23] := creerArbre(129,creerArbre(72,creerArbre(191,creerArbre(47,ARBREVIDE,ARBREVIDE),creerArbre(52,ARBREVIDE,creerArbre(52,ARBREVIDE,ARBREVIDE))),creerArbre(149,ARBREVIDE,ARBREVIDE)),creerArbre(125,creerArbre(98,creerArbre(77,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(78,creerArbre(5,creerArbre(27,ARBREVIDE,ARBREVIDE),creerArbre(110,ARBREVIDE,creerArbre(167,ARBREVIDE,ARBREVIDE))),creerArbre(95,ARBREVIDE,ARBREVIDE)))) ;
  exemple[24] := creerArbre(99,creerArbre(13,ARBREVIDE,creerArbre(3,ARBREVIDE,creerArbre(103,creerArbre(25,creerArbre(93,ARBREVIDE,ARBREVIDE),creerArbre(39,ARBREVIDE,creerArbre(172,ARBREVIDE,creerArbre(122,creerArbre(101,ARBREVIDE,ARBREVIDE),ARBREVIDE)))),creerArbre(87,ARBREVIDE,ARBREVIDE)))),creerArbre(102,ARBREVIDE,creerArbre(51,creerArbre(57,ARBREVIDE,creerArbre(94,creerArbre(87,ARBREVIDE,ARBREVIDE),creerArbre(192,ARBREVIDE,ARBREVIDE))),ARBREVIDE))) ;
  exemple[25] := creerArbre(199,ARBREVIDE,creerArbre(90,creerArbre(198,creerArbre(159,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(1,creerArbre(132,ARBREVIDE,creerArbre(153,ARBREVIDE,ARBREVIDE)),creerArbre(182,ARBREVIDE,creerArbre(16,creerArbre(57,creerArbre(67,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(34,ARBREVIDE,ARBREVIDE)))))) ;
  exemple[26] := creerArbre(16,creerArbre(13,creerArbre(54,creerArbre(193,ARBREVIDE,creerArbre(184,creerArbre(57,ARBREVIDE,ARBREVIDE),creerArbre(22,ARBREVIDE,creerArbre(110,ARBREVIDE,creerArbre(15,ARBREVIDE,ARBREVIDE))))),ARBREVIDE),creerArbre(177,ARBREVIDE,creerArbre(172,creerArbre(96,ARBREVIDE,ARBREVIDE),ARBREVIDE))),ARBREVIDE) ;
  exemple[27] := creerArbre(77,creerArbre(4,creerArbre(66,creerArbre(47,ARBREVIDE,ARBREVIDE),creerArbre(98,creerArbre(22,ARBREVIDE,creerArbre(35,creerArbre(80,ARBREVIDE,creerArbre(167,ARBREVIDE,ARBREVIDE)),creerArbre(23,creerArbre(146,creerArbre(97,ARBREVIDE,ARBREVIDE),ARBREVIDE),ARBREVIDE))),creerArbre(39,ARBREVIDE,ARBREVIDE))),creerArbre(161,creerArbre(96,ARBREVIDE,ARBREVIDE),creerArbre(191,creerArbre(92,ARBREVIDE,ARBREVIDE),ARBREVIDE))),creerArbre(45,ARBREVIDE,ARBREVIDE)) ;
  exemple[28] := creerArbre(46,creerArbre(14,creerArbre(30,ARBREVIDE,ARBREVIDE),creerArbre(31,creerArbre(122,ARBREVIDE,creerArbre(141,ARBREVIDE,creerArbre(184,ARBREVIDE,ARBREVIDE))),creerArbre(140,creerArbre(162,creerArbre(111,creerArbre(182,ARBREVIDE,ARBREVIDE),creerArbre(188,ARBREVIDE,creerArbre(38,ARBREVIDE,ARBREVIDE))),creerArbre(11,ARBREVIDE,ARBREVIDE)),ARBREVIDE))),creerArbre(196,creerArbre(138,ARBREVIDE,ARBREVIDE),creerArbre(16,ARBREVIDE,ARBREVIDE))) ;
  exemple[29] := creerArbre(2,creerArbre(95,creerArbre(98,ARBREVIDE,creerArbre(61,creerArbre(40,ARBREVIDE,creerArbre(174,ARBREVIDE,creerArbre(63,ARBREVIDE,ARBREVIDE))),creerArbre(33,creerArbre(156,ARBREVIDE,creerArbre(92,ARBREVIDE,ARBREVIDE)),ARBREVIDE))),creerArbre(81,ARBREVIDE,ARBREVIDE)),creerArbre(196,creerArbre(0,ARBREVIDE,ARBREVIDE),creerArbre(190,creerArbre(178,ARBREVIDE,creerArbre(43,ARBREVIDE,ARBREVIDE)),creerArbre(190,ARBREVIDE,ARBREVIDE)))) ;
  exemple[30] := creerArbre(85,creerArbre(160,creerArbre(38,ARBREVIDE,ARBREVIDE),creerArbre(93,creerArbre(196,creerArbre(192,creerArbre(150,ARBREVIDE,ARBREVIDE),creerArbre(11,ARBREVIDE,ARBREVIDE)),ARBREVIDE),ARBREVIDE)),creerArbre(35,creerArbre(23,creerArbre(156,creerArbre(178,ARBREVIDE,creerArbre(42,ARBREVIDE,ARBREVIDE)),creerArbre(24,creerArbre(178,ARBREVIDE,ARBREVIDE),creerArbre(156,ARBREVIDE,ARBREVIDE))),creerArbre(16,creerArbre(190,ARBREVIDE,ARBREVIDE),creerArbre(62,ARBREVIDE,ARBREVIDE))),ARBREVIDE)) ;
  exemple[31] := creerArbre(69,creerArbre(194,ARBREVIDE,creerArbre(4,creerArbre(18,ARBREVIDE,ARBREVIDE),creerArbre(21,ARBREVIDE,creerArbre(179,ARBREVIDE,ARBREVIDE)))),creerArbre(190,creerArbre(92,creerArbre(16,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(141,ARBREVIDE,ARBREVIDE))) ;
  exemple[32] := creerArbre(67,creerArbre(32,creerArbre(160,creerArbre(12,ARBREVIDE,creerArbre(162,creerArbre(178,ARBREVIDE,ARBREVIDE),creerArbre(192,ARBREVIDE,ARBREVIDE))),creerArbre(110,creerArbre(136,creerArbre(195,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(152,creerArbre(32,ARBREVIDE,ARBREVIDE),ARBREVIDE))),ARBREVIDE),creerArbre(4,creerArbre(70,creerArbre(198,ARBREVIDE,creerArbre(44,ARBREVIDE,ARBREVIDE)),creerArbre(28,ARBREVIDE,ARBREVIDE)),creerArbre(57,ARBREVIDE,creerArbre(41,ARBREVIDE,ARBREVIDE)))) ;
  exemple[33] := creerArbre(41,creerArbre(34,creerArbre(153,ARBREVIDE,ARBREVIDE),creerArbre(111,creerArbre(104,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(12,creerArbre(30,ARBREVIDE,ARBREVIDE),creerArbre(159,creerArbre(132,ARBREVIDE,ARBREVIDE),creerArbre(113,ARBREVIDE,ARBREVIDE)))) ;
  exemple[34] := creerArbre(23,creerArbre(126,ARBREVIDE,creerArbre(117,ARBREVIDE,ARBREVIDE)),creerArbre(58,creerArbre(153,creerArbre(114,ARBREVIDE,creerArbre(37,creerArbre(154,creerArbre(127,creerArbre(151,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(165,ARBREVIDE,ARBREVIDE)),ARBREVIDE)),creerArbre(189,ARBREVIDE,creerArbre(180,ARBREVIDE,creerArbre(11,ARBREVIDE,ARBREVIDE)))),creerArbre(5,ARBREVIDE,ARBREVIDE))) ;
  exemple[35] := creerArbre(59,creerArbre(138,creerArbre(36,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(197,creerArbre(3,creerArbre(88,ARBREVIDE,ARBREVIDE),creerArbre(195,creerArbre(49,ARBREVIDE,ARBREVIDE),creerArbre(38,creerArbre(66,ARBREVIDE,ARBREVIDE),creerArbre(105,ARBREVIDE,ARBREVIDE)))),creerArbre(119,creerArbre(62,creerArbre(96,ARBREVIDE,ARBREVIDE),creerArbre(160,creerArbre(172,ARBREVIDE,ARBREVIDE),creerArbre(192,ARBREVIDE,ARBREVIDE))),creerArbre(65,creerArbre(190,ARBREVIDE,ARBREVIDE),ARBREVIDE)))) ;
  exemple[36] := creerArbre(98,creerArbre(132,creerArbre(95,creerArbre(140,creerArbre(33,creerArbre(137,creerArbre(44,creerArbre(0,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(47,ARBREVIDE,ARBREVIDE)),ARBREVIDE),ARBREVIDE),creerArbre(58,ARBREVIDE,ARBREVIDE)),creerArbre(51,creerArbre(186,creerArbre(85,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(27,creerArbre(23,ARBREVIDE,creerArbre(5,ARBREVIDE,ARBREVIDE)),creerArbre(86,ARBREVIDE,ARBREVIDE)))),ARBREVIDE) ;
  exemple[37] := creerArbre(146,creerArbre(121,creerArbre(144,creerArbre(134,creerArbre(198,ARBREVIDE,ARBREVIDE),creerArbre(91,creerArbre(94,ARBREVIDE,ARBREVIDE),creerArbre(10,ARBREVIDE,ARBREVIDE))),creerArbre(50,creerArbre(52,ARBREVIDE,creerArbre(97,ARBREVIDE,ARBREVIDE)),creerArbre(195,creerArbre(30,ARBREVIDE,ARBREVIDE),ARBREVIDE))),creerArbre(11,ARBREVIDE,creerArbre(29,creerArbre(33,ARBREVIDE,creerArbre(21,ARBREVIDE,ARBREVIDE)),ARBREVIDE))),creerArbre(163,creerArbre(121,ARBREVIDE,ARBREVIDE),ARBREVIDE)) ;
  exemple[38] := creerArbre(103,creerArbre(83,creerArbre(23,creerArbre(12,creerArbre(134,ARBREVIDE,creerArbre(56,creerArbre(192,ARBREVIDE,creerArbre(181,ARBREVIDE,ARBREVIDE)),ARBREVIDE)),ARBREVIDE),ARBREVIDE),creerArbre(122,creerArbre(81,ARBREVIDE,ARBREVIDE),creerArbre(155,creerArbre(195,creerArbre(189,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(77,creerArbre(106,ARBREVIDE,ARBREVIDE),ARBREVIDE)))),ARBREVIDE) ;
  exemple[39] := creerArbre(190,creerArbre(99,creerArbre(130,creerArbre(102,creerArbre(108,creerArbre(173,ARBREVIDE,creerArbre(120,ARBREVIDE,creerArbre(50,creerArbre(81,ARBREVIDE,ARBREVIDE),ARBREVIDE))),creerArbre(22,ARBREVIDE,ARBREVIDE)),ARBREVIDE),ARBREVIDE),creerArbre(54,creerArbre(49,ARBREVIDE,creerArbre(189,ARBREVIDE,ARBREVIDE)),ARBREVIDE)),ARBREVIDE) ;
  exemple[40] := creerArbre(89,creerArbre(32,creerArbre(177,ARBREVIDE,ARBREVIDE),creerArbre(167,creerArbre(65,ARBREVIDE,ARBREVIDE),creerArbre(71,ARBREVIDE,creerArbre(166,ARBREVIDE,ARBREVIDE)))),creerArbre(130,ARBREVIDE,creerArbre(64,creerArbre(38,ARBREVIDE,ARBREVIDE),ARBREVIDE))) ;
  exemple[41] := creerArbre(146,creerArbre(187,ARBREVIDE,creerArbre(42,ARBREVIDE,creerArbre(140,ARBREVIDE,creerArbre(8,ARBREVIDE,ARBREVIDE)))),creerArbre(159,creerArbre(143,creerArbre(36,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(35,ARBREVIDE,creerArbre(110,ARBREVIDE,ARBREVIDE)))) ;
  exemple[42] := creerArbre(148,creerArbre(146,ARBREVIDE,ARBREVIDE),creerArbre(20,creerArbre(155,ARBREVIDE,ARBREVIDE),creerArbre(50,creerArbre(186,creerArbre(94,ARBREVIDE,ARBREVIDE),creerArbre(189,ARBREVIDE,ARBREVIDE)),creerArbre(29,creerArbre(80,ARBREVIDE,creerArbre(31,ARBREVIDE,creerArbre(34,ARBREVIDE,ARBREVIDE))),creerArbre(75,ARBREVIDE,ARBREVIDE))))) ;
  exemple[43] := creerArbre(51,creerArbre(16,ARBREVIDE,creerArbre(72,creerArbre(91,creerArbre(3,creerArbre(50,ARBREVIDE,creerArbre(24,ARBREVIDE,creerArbre(189,ARBREVIDE,ARBREVIDE))),ARBREVIDE),creerArbre(26,ARBREVIDE,ARBREVIDE)),creerArbre(164,ARBREVIDE,ARBREVIDE))),creerArbre(187,ARBREVIDE,ARBREVIDE)) ;
  exemple[44] := creerArbre(45,creerArbre(172,creerArbre(76,creerArbre(29,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(59,creerArbre(38,ARBREVIDE,ARBREVIDE),creerArbre(86,ARBREVIDE,creerArbre(4,ARBREVIDE,creerArbre(68,ARBREVIDE,ARBREVIDE))))),creerArbre(42,creerArbre(143,ARBREVIDE,ARBREVIDE),creerArbre(64,creerArbre(6,ARBREVIDE,ARBREVIDE),ARBREVIDE))) ;
  exemple[45] := creerArbre(198,creerArbre(29,creerArbre(129,ARBREVIDE,ARBREVIDE),creerArbre(190,creerArbre(196,creerArbre(108,ARBREVIDE,ARBREVIDE),creerArbre(171,ARBREVIDE,ARBREVIDE)),creerArbre(136,ARBREVIDE,creerArbre(66,ARBREVIDE,ARBREVIDE)))),creerArbre(171,creerArbre(11,creerArbre(35,creerArbre(156,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(38,creerArbre(133,ARBREVIDE,creerArbre(159,ARBREVIDE,ARBREVIDE)),creerArbre(100,ARBREVIDE,ARBREVIDE))),creerArbre(40,ARBREVIDE,creerArbre(193,ARBREVIDE,ARBREVIDE)))) ;
  exemple[46] := creerArbre(24,creerArbre(62,creerArbre(70,ARBREVIDE,ARBREVIDE),creerArbre(137,ARBREVIDE,ARBREVIDE)),creerArbre(134,creerArbre(44,creerArbre(74,ARBREVIDE,ARBREVIDE),creerArbre(122,ARBREVIDE,ARBREVIDE)),creerArbre(32,creerArbre(34,creerArbre(194,ARBREVIDE,ARBREVIDE),creerArbre(180,creerArbre(28,ARBREVIDE,ARBREVIDE),ARBREVIDE)),ARBREVIDE))) ;
  exemple[47] := creerArbre(70,creerArbre(55,creerArbre(92,ARBREVIDE,ARBREVIDE),creerArbre(33,creerArbre(45,creerArbre(53,ARBREVIDE,ARBREVIDE),creerArbre(86,creerArbre(157,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(116,creerArbre(128,creerArbre(14,creerArbre(1,ARBREVIDE,ARBREVIDE),ARBREVIDE),ARBREVIDE),creerArbre(135,creerArbre(138,ARBREVIDE,ARBREVIDE),creerArbre(56,creerArbre(132,ARBREVIDE,ARBREVIDE),ARBREVIDE))))),creerArbre(161,creerArbre(60,ARBREVIDE,ARBREVIDE),creerArbre(179,ARBREVIDE,ARBREVIDE))) ;
  exemple[48] := creerArbre(69,creerArbre(99,creerArbre(165,ARBREVIDE,ARBREVIDE),creerArbre(41,creerArbre(16,creerArbre(189,ARBREVIDE,ARBREVIDE),creerArbre(1,ARBREVIDE,ARBREVIDE)),creerArbre(91,creerArbre(24,ARBREVIDE,ARBREVIDE),creerArbre(68,ARBREVIDE,ARBREVIDE)))),creerArbre(150,creerArbre(35,ARBREVIDE,ARBREVIDE),creerArbre(41,creerArbre(7,creerArbre(18,ARBREVIDE,ARBREVIDE),creerArbre(62,creerArbre(167,ARBREVIDE,ARBREVIDE),creerArbre(30,ARBREVIDE,ARBREVIDE))),ARBREVIDE))) ;
  exemple[49] := creerArbre(160,creerArbre(187,creerArbre(108,ARBREVIDE,ARBREVIDE),creerArbre(151,creerArbre(41,ARBREVIDE,ARBREVIDE),ARBREVIDE)),creerArbre(26,creerArbre(82,ARBREVIDE,ARBREVIDE),creerArbre(65,creerArbre(44,creerArbre(106,ARBREVIDE,creerArbre(49,ARBREVIDE,ARBREVIDE)),ARBREVIDE),creerArbre(115,creerArbre(198,creerArbre(16,ARBREVIDE,ARBREVIDE),ARBREVIDE),creerArbre(17,ARBREVIDE,ARBREVIDE))))) ;
finalization
end.
